baseURL: "https://keebs.fehmer.info/"
languageCode: "en-us"
title: "keebs.fehmer.info"
theme: "novela"
pygmentsstyle: 'monokai'
paginate: 6
social:
    github: "https://github.com/fehmer"
    npm: "https://www.npmjs.com/~fehmer"
    xing: "https://www.xing.com/profile/Christian_Fehmer"
    email: "mailto:keebs//at//fehmer//dot/info"
taxonomies:
  author: authors
markup:
  goldmark:
    renderer:
      unsafe: true