baseURL: "https://keebs.fehmer.info/"
canonifyURLs: false
languageCode: "en-us"
title: "keebs/fehmer.info"
theme: "terminal"
pygmentsstyle: 'monokai'
paginate: 9999
social:
    www: "https://fehmer.info"
    github: "https://github.com/fehmer"
    npm: "https://www.npmjs.com/~fehmer"
    xing: "https://www.xing.com/profile/Christian_Fehmer"
    email: "mailto:keebs//at//fehmer//dot/info"
taxonomies:
  author: authors
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  favicon: images/favicon.svg
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: post
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: orange
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: false

